### PR TITLE
Refactored Cannelloni packet parsing and building to separate h/cpp files.

### PR DESCRIPTION
**Pull request by tuvok**
New files will be compiled as a separate shared object library allowing
easy integration of Cannelloni protocol within other applications.

The motivation for this change is a plan to integrate Cannelloni protocol handling in GENIVI CANdevStudio directly, without the need of creating local vcan devices.

### CODE REVIEW

**Comment by mguentner** [comment]
Closed with 6e1f4b7f9ec9a098f9850c71105107f40d0f1c55
I reworded your commit slightly, hence the checksum change.

Thanks for your contribution, looking forward to test it with CANdevStudio!

**Comment by mguentner** [comment]
Sorry. Merged prematurely.
When testing between two nodes, frames with no data section are not being recognized.

Reproduce:
`cannelloni -S s -I vcan0 -d cubt`
`cannelloni -S c -I vcan1 -R 127.0.0.1 -d cubt`

`cangen vcan0 -L 0`
Does not send anything to vcan1

**Comment by tuvok** [comment]
Hi, thanks for feedback. I will look into that on Monday when I'm back at the office.
Frames with no data sections - meaning those with len=0? That would make sense, since I discard them intentionally, I didn't know they were supposed to be transferred.
I needed a way to mark frame as incorrect for the frameReceiver callback, since in case of incorrect packet it still has to be called to deallocate frame, but such frame shouldn't be sent further. I will have to mark that in a different way.

**Comment by mguentner** [comment]
Empty frames can be used for signaling events or for monitoring purposes (heartbeat).

I did a quick check and this line seems to be the reason:
```patch
diff --git a/udpthread.cpp b/udpthread.cpp
index f6523f4..f7d142e 100644
--- a/udpthread.cpp
+++ b/udpthread.cpp
@@ -105,9 +105,6 @@ bool UDPThread::parsePacket(uint8_t *buffer, uint16_t len, struct sockaddr_in &c
         };
         auto receiver = [this](canfd_frame* f)
         { 
-            if (f->len == 0)
-                return;
-
             m_peerThread->transmitFrame(f);
             if (m_debugOptions.can)
             {
```

the frameReceiver function could have a second, boolean argument like `success`

Then this is possible:

```c++
if (success) {
  m_peerThread->transmitFrame(f);
} else {
  m_peerThread->getFrameBuffer()->insertFramePool(f);
}
```

btw: the `else` case is missing in the current code (bug) and should be included to prevent leakage

**Comment by tuvok** [comment]
Hmm, you are right, transmitFrame does return the buffer, but somehow I forgot to call the insertFrame manually in len==0 case...

**Comment by mguentner** [comment]
That is because I also forgot it...

**Comment by mguentner** [comment]
Thanks for the quick fix! I squashed the commits and changed the commit message again.
Since the packet parsing is now a separate file, unit tests are possible now :tada:

**Pull request closed without merging**
